### PR TITLE
Support for class component

### PR DESCRIPTION
**Pull request by akinoccc**
Support for class component and chang somthing about orginal template.

### CODE REVIEW

**Comment by dohooo** [comment]
I'm planning on refactoring this part of the template. Maybe we can let the user specify the template.

**Comment by akinoccc** [comment]
> I'm planning on refactoring this part of the template. Maybe we can let the user specify the template.

I think just add the template path configuration. I've done one of these projects before

**Comment by dohooo** [comment]
And you can let him use different templates for different paths under the project.

**Comment by akinoccc** [comment]
> And you can let him use different templates for different paths under the project.

Are you refactoring it now? if yes, look forward to your next commit.

**Comment by dohooo** [comment]
> > And you can let him use different templates for different paths under the project.
> 
> Are you refactoring it now? if yes, look forward to your next commit.

Do you use WeChat? We can talk about it hh

**Comment by akinoccc** [comment]
> Do you use WeChat? We can talk about it hh

WeChat: w_AmsChan

**Pull request closed without merging**
